[package]
name = "name-service-module"
version = "2.0.0"
authors = ["Hsiung"]
edition = "2018"

[dependencies]
serde = { version = "1.0.101", optional = true }
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
rstd = { package = "sp-std", path = "../../../primitives/sr-std", default-features = false }
runtime-io = { package = "sp-io", path = "../../../primitives/sr-io", default-features = false }
sp-runtime = { path = "../../../primitives/sr-primitives", default-features = false }
support = { package = "frame-support", path = "../../../frame/support", default-features = false }
system = { package = "frame-system", path = "../../../frame/system", default-features = false }
balances = { package = "pallet-balances", path = "../../../frame/balances", default-features = false }
primitives = { package = "sp-core", path = "../../../primitives/core", default-features = false }

[dev-dependencies]

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"rstd/std",
	"runtime-io/std",
	"sp-runtime/std",
	"support/std",
	"system/std",
	"balances/std",
	"primitives/std",
]
